services:
  - type: web
    name: buat-web-ujian-gratis
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PGSSLMODE
        value: require
      - key: DATABASE_URL
        sync: false
